// Generated by CoffeeScript 2.3.0
(function() {
  var Builder, LogstashFormatter;

  Builder = require("./Builder").Builder;

  LogstashFormatter = require("./LogstashFormatter").LogstashFormatter;

  describe("Builder", function() {
    var testedBuilder, testedHandler;
    testedBuilder = null;
    testedHandler = null;
    beforeEach(function() {
      return testedBuilder = new Builder;
    });
    describe("when built with default parameters", function() {
      beforeEach(function() {
        return testedHandler = testedBuilder.build();
      });
      it("handler contains default prefix", function() {
        return testedHandler.prefix.should.equal("./logs/configure-me.log");
      });
      it("handler contains default rotation threshold", function() {
        return testedHandler.rotationBytesThreshold.should.equal(104857600);
      });
      return it("handler contains default formatter", function() {
        return testedHandler.formatter.should.be.instanceOf(LogstashFormatter);
      });
    });
    return describe("when build with custom filePrefix", function() {
      var formatter, prefix, rotationThreshold;
      prefix = `./tmp/${new Date().getTime()}/test-`;
      rotationThreshold = 123444;
      formatter = {
        format: function(entry) {
          return 'test';
        }
      };
      beforeEach(function() {
        return testedHandler = testedBuilder.prefix(prefix).rotationBytesThreshold(rotationThreshold).formatter(formatter).build();
      });
      it("contains properly set prefix", function() {
        return testedHandler.prefix.should.equal(prefix);
      });
      it("contains properly set rotation threshold", function() {
        return testedHandler.rotationBytesThreshold.should.equal(rotationThreshold);
      });
      return it("contains properly set formatter", function() {
        return testedHandler.formatter.should.equal(formatter);
      });
    });
  });

}).call(this);

//# sourceMappingURL=Builder.spec.js.map
