// Generated by CoffeeScript 2.3.0
(function() {
  var Builder;

  Builder = require("./Builder").Builder;

  describe("Builder", function() {
    var testedBuilder, testedHandler;
    testedBuilder = null;
    testedHandler = null;
    beforeEach(function() {
      return testedBuilder = new Builder;
    });
    describe("when built with default parameters", function() {
      beforeEach(function() {
        return testedHandler = testedBuilder.build();
      });
      return it("handler contains default parameters", function() {
        return testedHandler.prefix.should.equal("./logs/configure-me.log");
      });
    });
    return describe("when build with custom filePrefix", function() {
      var prefix;
      prefix = `./tmp/${new Date().getTime()}/test-`;
      beforeEach(function() {
        return testedHandler = testedBuilder.prefix(prefix).build();
      });
      return it("contains properly set parameters", function() {
        return testedHandler.prefix.should.equal(prefix);
      });
    });
  });

}).call(this);

//# sourceMappingURL=Builder.spec.js.map
